export const metadata = {
    title: 'Users',
    description: 'Generated by create next app',
  }

  export default function UserLayout({ children }) {
    return (
        <div>
           <main>
                {children}
            </main>
        </div>
    )
}
    